import {
  home,
  inventory,
  sales,
  purchase,
  reports,
  documents,
} from "@/components/svgs";
// import { report } from "process";
// import { Url } from "url";

export interface subProps {
  [key: string]: any;
}

export const dashboard = [
  {
    id: 1,
    title: "Home",
    items: [{path: "/home" }],
    icon: home,
    collapse: false,
  },
  {
    id: 2,
    title: "Inventory",
    items: [
      { id: "2_1", title: "Items", path: "/inventory/items" },
      { id: "2_2", title: "Price Lists", path: "/inventory/price_lists" },
      {
        id: "2_3",
        title: "Inventory Adjustments",
        path: "/inventory/adjustments",
      },
    ],
    icon: inventory,
    collapse: true,
  },
  {
    id: 3,
    title: "Sales",
    items: [
      { id: "3_1", title: "Sales Orders", path: "/sales/orders" },
      { id: "3_2", title: "Sales Receipts", path: "/sales/receipts" },
      { id: "3_3", title: "Sales Return", path: "/sales/return" },
      { id: "3_4", title: "Invoices", path: "/sales/invoices" },
    ],
    icon: sales,
    collapse: true,
  },
  {
    id: 4,
    title: "Purchase",
    items: [
      { id: "4_1", title: "Expenses", path: "/purchase/expenses" },
      { id: "4_2", title: "Purchase Orders", path: "/purchase/orders" },
      { id: "4_3", title: "Bills", path: "/purchase/bills" },
      { id: "4_4", title: "Payments Made", path: "/purchase/payments" },
    ],
    icon: purchase,
    collapse: true,
  },
  {
    id: 5,
    title: "Reports",
    items: [{path: "/reports" }],
    icon: reports,
    collapse: false,
  },
  {
    id: 6,
    title: "Documents",
    items: [{path: "/documents" }],
    icon: documents,
    collapse: false,
  },
];

export const subcategories: subProps = {
  Accessories: [
    "Air Fresheners",
    "Air Horns",
    "Bicycle",
    "Bug Deflectors",
    "Bungees",
    "Cell Phone",
    "Cigarette Lighters",
    "Clock",
    "Covers",
    "Cup Holders",
    "Decals",
    "Floor Mats",
    "GPS Navigation",
    "Inner Tubes",
    "Interior Accessories",
    "Key Rings",
    "Keys",
    "License Plate Frames",
    "License Plates",
    "Locks",
    "Model and Toys",
    "Mugs",
    "Pet Accessories",
    "Radar Detector",
    "Remote Starters",
    "Repair Manuals",
    "Roadside Safety",
    "Roll Bars",
    "Roof Tops and Racks",
  ],
  "Air Intake": [
    "Air Cleaners",
    "Air Intake Hoses",
    "Air Intakes",
    "Airboxes",
    "Carburetor Chokes",
    "Carburetor Kits99",
    "Carburetors",
    "Intake Air Heaters",
    "Intake Manifolds",
    "Throttle Bodies",
    "Throttle Bodies & Carbs",
  ],
  "Alternators and Starters": [
    "Alternator Kits",
    "Alternator Pulleys",
    "Alternators",
    "Ignition Locks",
    "Starter Kits",
    "Starters",
    "Voltage Regulators",
  ],
  Apparel: ["Cold Weather", "Headware", "Shirts"],
  "Appearance and Paint": [
    "Buffers",
    "Degreasers",
    "Detailing and Finishing",
    "Exterior Care",
    "Garden Hoses",
    "Interior Care",
    "Paint Remover",
    "Paints",
    "Primers",
    "Stickers",
  ],
  "Audio and Video": [
    "Amplifiers",
    "Antennas",
    "Audio Jacks",
    "Harness Connectors",
    "Speakers",
    "Stereos",
    "Subwoofers",
    "Video and Consoles",
  ],
  "Batteries and Chargers": [
    "Automotive Batteries and Related",
    "Battery Cables and Terminals",
    "Battery Chargers",
    "Battery Sensors and Switches",
    "Deep Cycle Batteries",
    "Generators",
    "Golf Cart Batteries",
    "Heavy Duty Battery",
    "Household Battery",
    "Hybrid and EV",
    "Jump Starters",
    "Wheelchair Batteries",
  ],
  "Belts and Hoses": [
    "AN Fittings",
    "Belt Tensioners",
    "Braided Hoses",
    "Diesel Cigar Hoses",
    "Diesel Emissions Fluid Hoses",
    "Driveway Signal Hoses",
    "Duct Hoses",
    "Emission Balance Tube Hoses",
    "Engine Cooling Hoses",
    "Engine Hoses",
    "Flame Trap Hoses",
    "Fuel Hoses",
    "Heater Hoses",
    "Hose Clamps",
    "Hose Fittings",
    "Hose Reels",
    "Hoses",
    "Hydraulic Hoses",
    "Idle Valve Air Hoses",
    "Multi-Purpose Hoses",
    "Oil Cooler Hoses",
    "PCV Hoses",
    "Pre Heat Hoses",
    "Pulleys",
  ],
  Body: [
    "Bodies and Fenders",
    "Body Repair Tools",
    "Bumper Clips",
    "Bumper Covers",
    "Bumpers",
    "Caps",
    "Convertible Components",
    "Doors",
    "Gas Cap Covers",
    "Glass",
    "Grilles",
    "Hoods",
    "Latches and Handles",
    "Liftgates",
    "Mirror",
    "Mirrors",
    "Power Windows",
    "Roof Tops",
    "Sunroofs and Parts",
    "Truck Beds",
    "Trunk and Tailgate",
    "Windows",
    "Windshields",
  ],
  Braking: [
    "ABS Systems",
    "Air Brakes",
    "Brake Boosters",
    "Brake Cables",
    "Brake Calipers",
    "Brake Clutches",
    "Brake Hardware",
    "Brake Hoses",
    "Brake Hydraulics",
    "Brake Kits",
    "Brake Lines and Fittings",
    "Brake Master Cylinders",
    "Brake Pads and Shoes",
    "Brake Rotors and Drums",
    "Brake Sensors and Switches",
    "Parking Brakes",
    "Wheel Cylinders",
  ],
  "Clutch System": [
    "Clutch Assembly Bolts",
    "Clutch Bell Housing",
    "Clutch Bellcranks",
    "Clutch Cables",
    "Clutch Discs",
    "Clutch Forks",
    "Clutch Hoses",
    "Clutch Hydraulics",
    "Clutch Kits",
    "Clutch Master Cylinders",
    "Clutch Operating Shafts",
    "Clutch Pilot Bearings",
    "Clutch Pilot Bushings",
    "Clutch Pivot Balls",
    "Clutch Pressure Plates",
    "Clutch Push Rods",
    "Clutch Release Arms",
    "Clutch Release Bearings",
    "Clutch Release Lever Springs",
    "Clutch Shafts",
    "Clutch Slave Cylinders",
    "Flywheels",
  ],
  "Cooling and Climate Control": [
    "Air Conditioning",
    "Blend Door",
    "Blower Motor and Related",
    "Engine Cooling",
    "Expansion Tanks",
    "Heating",
    "HVAC Electrical",
  ],
  "Drive Shafts and Axles": ["Rear Axle Shaft Bearing"],
  Drivetrain: [
    "4WD Components",
    "CV Axles and Joints",
    "Differentials",
    "Drive Shafts and Axles",
    "Drivetrain Electrical",
    "Hubs and Hub Assemblies",
    "Spindles",
    "Transfer Cases",
    "Universal Joints",
  ],
  Electrical: [
    "AC Adapters",
    "ADAS",
    "Anti-Theft and Alarms",
    "Cruise Control",
    "Data Acquisition Module",
    "Disconnect Terminal",
    "Driving Safety Monitoring System",
    "Electrical Accessories",
    "Electrical Cables",
    "Electrical Connectors",
    "Electrical Motors",
    "Electronic Accessory",
    "Electronic Toll Device",
    "Engine Wiring Harnesses",
    "Exterior Wiring Harnesses",
    "Female Terminals",
    "Fuses",
    "Heads Up Display Assembly Bolt",
    "Heads Up Display Assembly Clip",
    "Insulators and Grommets",
    "Interior Wiring Harnesses",
    "Male Disconnect Terminal",
    "Outlet Adapters",
    "Pigtail Connectors",
    "Switches, Sensors & Relays",
  ],
  Engine: [
    "Camshafts",
    "Crankshaft Pulley and Harmonic Balancer",
    "Engine Blocks",
    "Engine Control Modules (ECM)",
    "Engine Covers",
    "Engine Gaskets and Seals",
    "Engine Internal",
    "Engine Kits",
    "Engine Mounts",
    "Engine Oil Dipsticks",
    "Engine Oil Lines",
    "Engine O-Ring and Hardware",
    "Engine Switches, Sensors and Relays",
    "Engine Timing",
    "Freeze and Expansion Plugs",
    "Intercoolers",
    "Oil Coolers",
    "Oil Delivery",
    "Oil Pans",
    "Oil Pumps",
    "Remanufactured Engines",
    "Superchargers",
    "Turbochargers",
    "Valve Cover and Cylinder Head",
  ],
  Exhaust: [
    "Catalytic Converters",
    "Coupler Reducers",
    "Exhaust Back Pressure Regulators",
    "Exhaust Brake Actuators",
    "Exhaust Cutouts",
    "Exhaust Elbows",
    "Exhaust Fittings",
    "Exhaust Flares",
    "Exhaust Flex Connectors",
    "Exhaust Gaskets",
    "Exhaust Hangers",
    "Exhaust Hardware",
    "Exhaust Heat Shields",
    "Exhaust Manifold and Headers",
    "Exhaust Mufflers",
    "Exhaust Pipes",
    "Exhaust Plugs",
    "Exhaust System Kits",
    "Exhaust Temperature (EGT)",
    "Exhaust Tips",
    "Exhaust Tubing",
  ],
  "Filters and PCV": [
    "Air Filters",
    "Cabin Air Filters",
    "Fuel Filters",
    "Hydraulic Filters",
    "Oil Filters",
    "Positive Crankcase Ventilation (PCV)",
    "Transmission Filters",
  ],
  "Fluids and Chemicals": [
    "Adhesives",
    "Cleaners",
    "Compounds",
    "Coolant/Antifreeze",
    "Deicers",
    "Engine Additives",
    "Fluids",
    "Fuel Treatments",
    "Refrigerants",
    "Sealants",
    "Service Interval",
    "Transmission Additives",
    "Transmission Fluids",
    "Treatments",
  ],
  "Fuel and Emissions System": [
    "Air Flow Sensors",
    "Air Injection",
    "Air Pumps",
    "Auxiliary Air Valves",
    "Canister Purge System",
    "Canister Purge Valves",
    "Crankcase Breather Hoses",
    "Diesel Emissions",
    "Diesel Fuel Injectors",
    "EGR Valves",
    "Emission Controls",
    "Emissions",
    "Emissions Hardware",
    "Exhaust Gas Recirculation (EGR)",
    "Fuel Injector Connectors",
    "Fuel Injector Electrical",
    "Fuel Injector Relays",
    "Fuel Injectors",
    "Fuel Lines",
    "Fuel Pumps",
    "Fuel Rails",
    "Fuel Sensors",
    "Fuel Tanks",
    "Fuel Wiring Connectors",
    "Gas Caps",
    "Idle Air Control",
    "Oxygen Sensors",
    "Smog",
    "Vacuum Distributors",
    "Vacuum Pumps",
    "Vacuum Valves",
    "Vapour Canister Purge Valves",
  ],
  "Ignition and Tune-Up": [
    "Distributors",
    "Glow Plugs",
    "Ignition Boots",
    "Ignition Coils",
    "Ignition Coils and Boots",
    "Ignition Connectors",
    "Ignition Electronics",
    "Ignition Kits",
    "Ignition Modules",
    "Ignition Sensors",
    "Ignition Switches",
    "Ignition Wires",
    "Spark Plugs",
  ],
  Interior: [
    "Adjustable Pedals",
    "Airbags",
    "Brake Pedals",
    "Car USB Ports",
    "Carpets",
    "Clutch Pedals",
    "Dashboard",
    "Gas Pedals",
    "Gauges",
    "Glove Boxes",
    "Hazard Warning",
    "Headliner and Related",
    "Horn Parts",
    "Instrument Panels",
    "Knobs",
    "Seat Belts",
    "Seat Covers and Hardware",
    "Seats",
    "Steering Column",
    "Steering Wheels",
  ],
  "Jacks, Garage and Equipment": [
    "Fasteners",
    "Garage Floor, Storage & Accessories",
    "Garage Lifts",
    "Jacks",
    "Nuts and Bolts",
    "Parts Washers",
    "Plugs",
    "Shop Equipment",
    "Storage and Containers",
    "Workwear and Gloves",
  ],
  "Lawn and Garden": [
    "Lawn and Garden Equipment",
    "Small Engine Batteries",
    "Trimmer Lines",
  ],
  Lighting: [
    "Exterior Lighting",
    "Headlights",
    "Instrument Panel Lighting",
    "Interior Lighting",
    "Lighting Switches, Sensors and Relays",
    "Signal Flashers",
    "Tail, Stop and Turn Lights",
  ],
  "Marine and RV": [
    "Air Mattresses",
    "Bilge Pumps",
    "Engine Gaskets",
    "Fishing Rod Holder",
    "Lights, Accessories and Electrical",
    "Marine Lubricants",
    "Portable Stoves",
    "Protective Covers",
    "RV Coolant/Antifreeze",
  ],
  "Motorcycle and ATV": [
    "Head Protection",
    "Helmets",
    "Motorcycle and ATV Batteries",
    "Motorcycle Parts",
    "Powersport Accessories",
  ],
  "Oil and Lubricants": [
    "Absorbent",
    "Greases",
    "Lubricants",
    "Motor Oil",
    "Penetrating and Fogging Oil",
  ],
  "Performance and Racing": [
    "Aftermarket Superchargers",
    "Aftermarket Turbochargers",
    "Nitrous and CO2 Systems",
    "Performance Air Cleaners",
    "Performance Air Filters",
    "Performance Air Intake Kits",
    "Performance Alternators",
    "Performance Batteries",
    "Performance Brakes",
    "Performance Clutches",
    "Performance Computers",
    "Performance Differentials",
    "Performance Distributors",
    "Performance Drivetrains",
    "Performance Engine",
    "Performance Engines",
    "Performance Exhaust",
    "Performance Fender Reinforcing Bars",
    "Performance Flexplates",
    "Performance Flywheels",
    "Performance Fuel Systems",
    "Performance Generators",
    "Performance Ignitions",
    "Performance Lift Kits",
    "Performance Lighting",
    "Performance Mufflers",
    "Performance Oil Filters",
    "Performance Oil Pans",
    "Performance Radiators",
    "Performance Shifters",
    "Performance Skid Plates",
    "Performance Starters",
    "Performance Steering",
    "Performance Suspension",
    "Performance Timing Covers",
    "Performance Transmissions",
    "Performance Valve Covers",
    "Performance Wheels",
    "Programmers",
    "Racing Pulleys",
    "Roll and Launch Control",
  ],
  "Steering and Chassis": [
    "Alignment Hardware",
    "Alignment Kits",
    "Ball Joints",
    "Bell Cranks",
    "Camber Kits",
    "Chassis",
    "Chassis Wiring Connectors",
    "Drive Shafts",
    "Gear Boxes",
    "Idler Arms",
    "King Pins",
    "Pitman Arms",
    "Power Steering",
    "Radius Arms",
    "Steering Arms",
    "Steering Bars",
    "Steering Bearing",
    "Steering Columns",
    "Steering Dampers",
    "Steering Hardware",
    "Steering Kits",
    "Steering Knuckles",
    "Steering Shafts",
    "Strut Rods",
    "Sway Bars",
    "Tie Rods",
    "Toe Kits",
  ],
  Suspension: [
    "Air Suspension and Kits",
    "Coil and Leaf Springs",
    "Control Arms",
    "Shocks and Struts",
    "Stability Control",
    "Suspension Control Modules",
    "Suspension Hardware",
    "Trailing Arms",
  ],
  Tools: [
    "Air Tools",
    "Alignment Tools",
    "Brake Tools",
    "Clutch Tools",
    "Commercial Tools and Equipment",
    "CV Joint Boot Installation Tools",
    "Diagnostic Tools",
    "Drills",
    "Drivetrain Axle Tools",
    "Electrical System Tools",
    "Engine Tools",
    "Exhaust Tools",
    "Fuel System Tools",
    "Grease Guns",
    "Hand Tools",
    "HVAC Tools",
    "Miscellaneous Specialty Tools",
    "Pliers",
    "Plumbing Tools and Assembly lube",
    "Power Tool Batteries",
    "Power Tools and Accessories",
    "Quick Disconnect Tools",
    "Ratchets",
    "Screwdrivers",
    "Screws",
    "Sockets",
    "Spark Plug Tools",
    "Speciality Tools",
    "Steering Tools",
    "Suspension Tools",
    "Thread Repair Kits",
    "Tyre Tools",
    "Tire Valves",
    "Tool Bag",
    "Tools and Accessories",
    "Transmission Coolers",
    "Trim and Exterior Tools",
    "Welding",
    "Wrenches",
  ],
  Towing: [
    "Fifth Wheel Hitches",
    "Gooseneck Hitches",
    "Receiver Hitches",
    "Tow Hooks",
    "Tow Rope and Strap",
    "Towing Mirror",
    "Trailer and Towing Accessories",
    "Trailer Bearings",
    "Trailer Brake Controls",
    "Trailer Couplers",
    "Trailer Hitches",
    "Trailer Wiring",
    "Winches",
  ],
  Transmission: [
    "Automatic Transmission Bands",
    "Automatic Transmission Kits",
    "Automatic Transmission Pan and Gasket",
    "Automatic Transmissions",
    "Back-Up Neutral Safety",
    "Bellhousings",
    "Final Drive",
    "Gear Shifters and Cables",
    "Manual Transmission Gaskets",
    "Manual Transmission Kits",
    "Manual Transmissions",
    "Miscellaneous Hardware and Bushing",
    "Torque Converter and Related",
    "Transmission Electrical",
    "Transmission Bearings",
    "Transmission Connectors",
    "Transmission Cooler and Parts",
    "Transmission Electrical",
    "Transmission Flexplate",
    "Transmission Mounts",
    "Transmission Seals",
  ],
  "Wheels and Tyres": [
    "Hubcaps",
    "Spare Tyre Kit",
    "Tyre and Wheel Care",
    "Tyres",
    "TPMS Sensor Kits",
    "TPMS Sensors",
    "Wheel Bearings",
    "Wheel Hardware",
    "Wheel Rims",
    "Wheel Seals",
    "Wheel Spacers",
    "Wheel Studs",
  ],
  "Wipers and Related": [
    "Front and Rear Wiper Blades",
    "Washer Pumps and Reservoir",
    "Windshield Washer Fluid",
    "Windshield Wiper Arms",
    "Windshield Wiper Hardware",
    "Windshield Wiper Kits",
    "Windshield Wiper Motors",
    "Windshield Wiper Nozzles",
    "Wiper Electrical",
  ],
};

export const categories = [
  "Accessories",
  "Air Intake",
  "Alternators and Starters",
  "Apparel",
  "Appearance and Paint",
  "Audio and Video",
  "Batteries and Chargers",
  "Belts and Hoses",
  "Body",
  "Braking",
  "Clutch System",
  "Cooling and Climate Control",
  "Drive Shafts and Axles",
  "Drivetrain",
  "Electrical",
  "Engine",
  "Exhaust",
  "Filters and PCV",
  "Fluids and Chemicals",
  "Fuel and Emissions System",
  "Ignition and Tune-Up",
  "Interior",
  "Jacks, Garage and Equipment",
  "Lawn and Garden",
  "Lighting",
  "Marine and RV",
  "Motorcycle and ATV",
  "Oil and Lubricants",
  "Performance and Racing",
  "Steering and Chassis",
  "Suspension",
  "Tools",
  "Towing",
  "Transmission",
  "Wheels and Tires",
  "Wipers and Related",
];

export const currencies = [
  "AED- UAE Dirham",
  "AUD- Australian Dollar",
  "CAD- Canadian Dollar",
  "CNY- Yuan Renminbi",
  "EUR- Euro",
  "GBP- Pound Sterling",
  "INR- Indian Rupee",
  "JPY- Japanese Yen",
  "NGN- Nigerian Naira",
  "SAR- Saudi Riyal",
  "USD- United States Dollar",
  "ZAR- South African Rand",
];

export const autoparts = {
  err: "No Records Found",
  header: [
    {
      text: "NAME",
      locked: true,
    },
    {
      text: "SKU",
      locked: false,
    },
    {
      text: "STOCK IN HAND",
      locked: false,
    },
    {
      text: "REORDER LEVEL",
      locked: false,
    },
    {
      text: "DESCRIPTION",
      locked: false,
    },
    {
      text: "MANUFACTURER",
      locked: false,
    },
    {
      text: "EAN",
      locked: false,
    },
    {
      text: "MPN",
      locked: false,
    },
    {
      text: "ENN",
      locked: false,
    },
    {
      text: "PURCHASE RATE",
      locked: false,
    },
  ],
};

export const pricelist = {
  err: "Special deals for regular customers Or customized prices for overseas clients",
  header: [
    {
      text: "NAME",
      locked: true,
    },
    {
      text: "DETAILS",
      locked: false,
    },
    {
      text: "CURRENCY",
      locked: false,
    },
    {
      text: "BULK PRICE",
      locked: false,
    },
  ],
};
